// BASE DE DATOS COMPLETA DE PRODUCTOS - SOUKAINA PURE
const productos = [
    // --- NOVEDADES Y SALUD GENERAL ---
    { 
        id: 1, 
        name: "Forever Absorbent-D", 
        price: 197, 
        category: "Bienestar",
        image: "assets/p1.jpg", 
        descShort: "Vitamina D3 y E masticables con sabor a higo chumbo.",
        descFull: "Refuerza la salud de los huesos, músculos y el sistema inmunitario. Ideal para combatir fatiga, migrañas y falta de sol.",
        ingredients: "Vitamina D3, Vitamina E, jugo de Higo Chumbo en polvo.",
        tag: "Nuevo" 
    },
    { 
        id: 2, 
        name: "Forever AloeTurm", 
        price: 90, 
        category: "Bienestar",
        image: "assets/p2.jpg", 
        descShort: "Pastillas blandas de cúrcuma y zinc con tecnología hidrogel.",
        descFull: "Apoyo inmunológico y confort articular. Tecnología hidrogel que garantiza una absorción superior de la curcumina.",
        ingredients: "Extracto de Cúrcuma, Zinc, Gel de Aloe Vera, Lecitina de Soja.",
        tag: "Nuevo" 
    },
    { 
        id: 3, 
        name: "Forever Marine Collagen", 
        price: 1077, 
        category: "Cosmética",
        image: "assets/p3.jpg", 
        descShort: "3000 mg de colágeno marino concentrado para piel y articulaciones.",
        descFull: "Mejora la elasticidad de la piel, frena las arrugas, fortalece el cabello y disminuye la fragilidad de las uñas.",
        ingredients: "Colágeno Marino, Vitaminas C y A, Biotina, Zinc, CoQ10, Goji.",
        tag: "Top Ventas" 
    },
    { 
        id: 4, 
        name: "Forever Bhringraj Hair Oil", 
        price: 160, 
        category: "Cuidado Personal",
        image: "assets/p4.jpg", 
        descShort: "Aceite capilar tradicional contra la caída y el encanecimiento.",
        descFull: "Conocido como el rey de las hierbas para el pelo. Nutre la raíz, estimula el crecimiento, elimina la caspa y repara puntas dañadas.",
        ingredients: "Bhringraj, Amla, Aloe Vera, Argán, Sésamo, Coco, Romero, Neem.",
        tag: "Recomendado" 
    },
    { 
        id: 5, 
        name: "Dream by Forever (Mujer)", 
        price: 84, 
        category: "Cuidado Personal",
        image: "assets/p5.jpg", 
        descShort: "Desodorante en spray femenino suave con doble concentración de perfume.",
        descFull: "Sin aluminio ni parabenos. Protege contra el mal olor mientras hidrata la piel axilar sensible gracias al gel de Aloe Vera.",
        ingredients: "Gel de Aloe Vera, Aceite de Mandarina, Aceite de Pimienta Rosa.",
        tag: "Nuevo" 
    },
    { 
        id: 6, 
        name: "Desire by Forever (Hombre)", 
        price: 84, 
        category: "Cuidado Personal",
        image: "assets/p6.jpg", 
        descShort: "Desodorante masculino en spray con aroma cítrico y amaderado.",
        descFull: "Formula segura sin aluminio ni gas comprimido. Rinde más de 1000 pulverizaciones protegiendo la piel sensible.",
        ingredients: "Gel de Aloe Vera, Aceite de Limón, Aceite de Mandarina.",
        tag: "Nuevo" 
    },
    { 
        id: 7, 
        name: "Radiance Facial Cleanser", 
        price: 113, 
        category: "Cosmética",
        image: "assets/p7.jpg", 
        descShort: "Limpiador facial iluminador con regaliz y bambú.",
        descFull: "Limpia profundamente eliminando suciedad e impurezas. Exfoliación suave que aporta luminosidad sin resecar la piel.",
        ingredients: "Gel de Aloe Vera, Extracto de Regaliz, Bambú, Glicerina.",
        tag: "Nuevo" 
    },
    { 
        id: 8, 
        name: "Radiance Moisturiser", 
        price: 155, 
        category: "Cosmética",
        image: "assets/p8.jpg", 
        descShort: "Crema hidratante ligera con aceite de Moringa y Azafrán.",
        descFull: "Ofrece hidratación profunda durante 24h, reduce rojeces y unifica el tono facial para una piel radiante.",
        ingredients: "Aloe Vera, Aceite de Moringa, Jojoba, Germen de Trigo, Azafrán.",
        tag: "Nuevo" 
    },

    // --- BEBIDAS DE ALOE VERA ---
    { 
        id: 9, 
        name: "Forever Aloe Vera Gel", 
        price: 425, 
        category: "Bienestar",
        image: "assets/p9.jpg", 
        descShort: "99.7% gel puro de Aloe Vera estabilizado sin conservantes.",
        descFull: "Limpia el sistema digestivo, favorece la digestión, equilibra la flora intestinal y refuerza las defensas naturales.",
        ingredients: "99.7% Gel de Aloe Vera estabilizado, Vitamina C.",
        tag: "Top Ventas" 
    },
    { 
        id: 10, 
        name: "Forever Aloe Vera Gel Mini (330ml)", 
        price: 142, 
        category: "Bienestar",
        image: "assets/p10.jpg", 
        descShort: "Formato individual compacto de 330ml de Gel puro de Aloe Vera.",
        descFull: "Mismas propiedades depurativas y digestivas del formato original en envase portátil ideal para llevar de viaje.",
        ingredients: "99.7% Gel de Aloe Vera estabilizado, Vitamina C.",
        tag: "Práctico" 
    },
    { 
        id: 11, 
        name: "Forever Aloe Berry Nectar", 
        price: 425, 
        category: "Bienestar",
        image: "assets/p11.jpg", 
        descShort: "Aloe Vera enriquecido con arándanos rojos y manzana.",
        descFull: "Ideal para el cuidado de las vías urinarias, riñones, circulación y aparato respiratorio con un delicioso sabor a frutos rojos.",
        ingredients: "90.7% Gel de Aloe Vera, Extracto de Arándanos rojos y Manzana.",
        tag: "Top Ventas" 
    },
    { 
        id: 12, 
        name: "Forever Aloe Berry Nectar Mini (330ml)", 
        price: 142, 
        category: "Bienestar",
        image: "assets/p12.jpg", 
        descShort: "Formato mini de 330ml de Berry Nectar.",
        descFull: "Cuidado urinario y digestivo portátil con arándanos y manzana.",
        ingredients: "Gel de Aloe Vera, Arándano rojo, Manzana.",
        tag: "Práctico" 
    },
    { 
        id: 13, 
        name: "Forever Aloe Peaches", 
        price: 462, 
        category: "Bienestar",
        image: "assets/p13.jpg", 
        descShort: "Aloe Vera combinado con concentrado natural de melocotón.",
        descFull: "Sabroso refresco que apoya la digestión y el sistema inmune. Su sabor dulce lo hace el favorito de los niños.",
        ingredients: "84.5% Gel de Aloe Vera, Jugo concentrado de Melocotón.",
        tag: "Recomendado" 
    },
    { 
        id: 14, 
        name: "Forever Aloe Peaches Mini (330ml)", 
        price: 154, 
        category: "Bienestar",
        image: "assets/p14.jpg", 
        descShort: "Formato portátil de 330ml sabor melocotón dulce.",
        descFull: "Aporta nutrientes, vitaminas y digestive boost con delicioso sabor frutal.",
        ingredients: "Gel de Aloe Vera, Melocotón concentrado.",
        tag: "Práctico" 
    },
    { 
        id: 15, 
        name: "Forever Aloe Mango", 
        price: 425, 
        category: "Bienestar",
        image: "assets/p15.jpg", 
        descShort: "Gel de Aloe Vera infundido con puré de mango natural.",
        descFull: "Rico en antioxidantes y vitamina C. Ayuda a depurar toxinas, mejorar la digestión y aportar energía fresca al día a día.",
        ingredients: "Gel de Aloe Vera, Puré de Mango natural, Vitamina C.",
        tag: "Nuevo" 
    },

    // --- PRODUCTOS DE LA COLMENA ---
    { 
        id: 16, 
        name: "Forever Bee Propolis", 
        price: 520, 
        category: "Bienestar",
        image: "assets/p16.jpg", 
        descShort: "Antibiótico natural a base de própolis de abeja puro.",
        descFull: "Fortalece las defensas del cuerpo ante gripes, bacterias estomacales y afecciones de garganta o pulmones.",
        ingredients: "Própolis de abeja, Proteína de Soja, Miel, Jalea Real.",
        tag: "Top Ventas" 
    },
    { 
        id: 17, 
        name: "Forever Royal Jelly", 
        price: 539, 
        category: "Bienestar",
        image: "assets/p17.jpg", 
        descShort: "Jalea real pura para combatir el cansancio físico y mental.",
        descFull: "Estimulante natural del sistema nervioso y metabólico. Favorece la concentración, la fertilidad y la salud de la piel.",
        ingredients: "Jalea Real de abeja concentrada.",
        tag: "Recomendado" 
    },
    { 
        id: 18, 
        name: "Forever Bee Pollen", 
        price: 248, 
        category: "Bienestar",
        image: "assets/p18.jpg", 
        descShort: "Polen de abeja natural para energía y apetito.",
        descFull: "Superalimento rico en vitaminas y minerales. Aumenta la resistencia, abre el apetito y combate estados anémicos.",
        ingredients: "Polen de abeja, Miel pura.",
        tag: "Top Ventas" 
    },
    { 
        id: 19, 
        name: "Forever Bee Honey", 
        price: 270, 
        category: "Bienestar",
        image: "assets/p19.jpg", 
        descShort: "Miel de montaña 100% pura y natural.",
        descFull: "Fuente rápida de energía natural y sustituto saludable del azúcar refinado. Calma la garganta y apoya la inmunidad.",
        ingredients: "Miel pura de flores de montaña.",
        tag: "Top Ventas" 
    },

    // --- NUTRICIÓN Y SUPLEMENTOS ---
    { 
        id: 20, 
        name: "Forever Active Pro-B", 
        price: 483, 
        category: "Bienestar",
        image: "assets/p20.jpg", 
        descShort: "8 mil millones de bacterias con 6 cepas de probióticos.",
        descFull: "Restaura la flora intestinal, combate gases, hinchazón, estreñimiento y colon irritable mejorando la absorción de nutrientes.",
        ingredients: "6 cepas probióticas patentadas, Fibra prebiótica.",
        tag: "Top Ventas" 
    },
    { 
        id: 21, 
        name: "Forever Fields of Greens", 
        price: 196, 
        category: "Bienestar",
        image: "assets/p21.jpg", 
        descShort: "Concentrado verde de cebada, trigo y alfalfa.",
        descFull: "Rico en clorofila y minerales. Favorece la circulación, ayuda a controlar la glucosa en sangre y regula el tránsito intestinal.",
        ingredients: "Brotes de Cebada, Trigo, Alfalfa y Pimienta de Cayena.",
        tag: "Económico" 
    },
    { 
        id: 22, 
        name: "Forever Supergreens", 
        price: 507, 
        category: "Bienestar",
        image: "assets/p22.jpg", 
        descShort: "Mezcla antioxidante de más de 20 frutas y verduras.",
        descFull: "Sobres individuales ricos en vitaminas C y E. Alcaliniza el pH corporal, combate la fatiga y nutre las células en profundidad.",
        ingredients: "Espinacas, Brócoli, Aloe Vera, Goji, Té verde, Frutos rojos.",
        tag: "Recomendado" 
    },
    { 
        id: 23, 
        name: "Forever Fiber", 
        price: 327, 
        category: "Bienestar",
        image: "assets/p23.jpg", 
        descShort: "5 gramos de fibra soluble para disolver en líquidos.",
        descFull: "Promueve la saciedad en dietas de control de peso, elimina el estreñimiento y regula el nivel de azúcar y colesterol.",
        ingredients: "Mezcla patentada de fibras solubles de rápida disolución.",
        tag: "Recomendado" 
    },
    { 
        id: 24, 
        name: "Forever Garlic-Thyme", 
        price: 296, 
        category: "Bienestar",
        image: "assets/p24.jpg", 
        descShort: "Cápsulas inodoras de Ajo y Tomillo concentrado.",
        descFull: "Potente antiséptico para el sistema respiratorio y cardiovascular. Ayuda a regular la presión arterial y desinfecta la flora digestiva.",
        ingredients: "Aceite concentrado de Ajo y Tomillo en cápsulas blandas.",
        tag: "Top Ventas" 
    },
    { 
        id: 25, 
        name: "Forever Kids", 
        price: 227, 
        category: "Bienestar",
        image: "assets/p25.jpg", 
        descShort: "Multivitamínico masticable en forma de animales para niños.",
        descFull: "Aporta 12 vitaminas y minerales clave extraídos de frutas y verduras para un crecimiento sano y apertura del apetito.",
        ingredients: "Vitaminas A, C, D, B12, Hierro, Zinc, concentrado de frutas.",
        tag: "Popular" 
    },
    { 
        id: 26, 
        name: "Forever Daily", 
        price: 275, 
        category: "Bienestar",
        image: "assets/p26.jpg", 
        descShort: "55 nutrientes esenciales con complejo AOS antioxidante.",
        descFull: "Fórmula avanzada que cubre todas las deficiencias nutricionales diarias de adultos, proporcionando energía continua.",
        ingredients: "20 extractos de frutas y verduras, Complejo AOS, 12 Vitaminas.",
        tag: "Recomendado" 
    },
    { 
        id: 27, 
        name: "Forever iVision", 
        price: 477, 
        category: "Bienestar",
        image: "assets/p27.jpg", 
        descShort: "Protección ocular avanzada frente a la luz azul y pantallas.",
        descFull: "Protege la vista contra la fatiga digital y la luz solar. Contiene carotenoides esenciales para conservar una visión nítida.",
        ingredients: "Lutemax 2020 (Luteína, Zeaxantina), Vitaminas A, C, E, Zinc.",
        tag: "Nuevo" 
    },
    { 
        id: 28, 
        name: "Vitolize Men", 
        price: 458, 
        category: "Bienestar",
        image: "assets/p28.jpg", 
        descShort: "Suplemento para el bienestar prostático y hormonal masculino.",
        descFull: "Favorece la salud de la próstata, el flujo urinario normal, regula la testosterona y combate el cansancio íntimo.",
        ingredients: "Semillas de Calabaza, Pygeum, Vitaminas C, D, E, B6, Zinc, Licopeno.",
        tag: "Top Ventas" 
    },
    { 
        id: 29, 
        name: "Vitolize Women", 
        price: 418, 
        category: "Bienestar",
        image: "assets/p29.jpg", 
        descShort: "Equilibrio hormonal y urinario para la mujer.",
        descFull: "Alivia las molestias menstruales, síntomas de la menopausia, retención de líquidos y estados de molestia en las vías urinarias.",
        ingredients: "Manzana, Arándano rojo, Pasiflora, Magnesio, Vitaminas D, B12.",
        tag: "Top Ventas" 
    },
    { 
        id: 30, 
        name: "Forever ImmuBlend", 
        price: 327, 
        category: "Bienestar",
        image: "assets/p30.jpg", 
        descShort: "Fórmula de hongos Shiitake y Maitake para las defensas.",
        descFull: "Refuerzo biológico para el sistema inmunitario. Ayuda a combatir la astenia estacional y el estrés biológico en épocas de frío.",
        ingredients: "Hongos Maitake y Shiitake, Lactoferrina, Zinc, Vitamina C y D.",
        tag: "Recomendado" 
    },
    { 
        id: 31, 
        name: "Forever Absorbent-C", 
        price: 287, 
        category: "Bienestar",
        image: "assets/p31.jpg", 
        descShort: "Vitamina C unida a salvado de avena para máxima absorción.",
        descFull: "Poderoso antioxidante. La avena permite que la Vitamina C permanezca más tiempo en el cuerpo reforzando encías, piel y defensas.",
        ingredients: "Vitamina C natural, Salvado de Avena pura, Miel.",
        tag: "Top Ventas" 
    },
    { 
        id: 32, 
        name: "Forever Move", 
        price: 821, 
        category: "Bienestar",
        image: "assets/p32.jpg", 
        descShort: "Membrana de cáscara de huevo NEM y cúrcuma para articulaciones.",
        descFull: "Demostrado clínicamente para mejorar la flexibilidad y reducir la rigidez articular en solo 7 a 10 días de uso continuo.",
        ingredients: "Membrana NEM de huevo, BioCurc (Cúrcuma de alta solubilidad).",
        tag: "Top Ventas" 
    },
    { 
        id: 33, 
        name: "Forever Calcium", 
        price: 394, 
        category: "Bienestar",
        image: "assets/p33.jpg", 
        descShort: "Cinturón mineral de Calcio, Magnesio y Vitamina D.",
        descFull: "Fortalece la estructura ósea y dental. Previene la osteopenia y los calambres musculares con una fórmula de fácil asimilación.",
        ingredients: "Bisglicinato de Calcio, Magnesio, Zinc, Manganeso, Vitamina D.",
        tag: "Recomendado" 
    },
    { 
        id: 34, 
        name: "Forever Arctic Sea", 
        price: 516, 
        category: "Bienestar",
        image: "assets/p34.jpg", 
        descShort: "Omega 3 (pescado y calamar) con Omega 9 (aceite de oliva).",
        descFull: "Protege la salud cardiovascular, regula el colesterol, activa la memoria, mejora la visión y disminuye la inflamación articular.",
        ingredients: "Aceite de pescado puro, Aceite de Calamar, Aceite de Oliva virgen extra.",
        tag: "Top Ventas" 
    },
    { 
        id: 35, 
        name: "Forever Active HA", 
        price: 440, 
        category: "Bienestar",
        image: "assets/p35.jpg", 
        descShort: "Ácido Hialurónico oral con aceite de Jengibre y Cúrcuma.",
        descFull: "Lubrica y amortigua las articulaciones rígidas, mejorando la movilidad y aportando hidratación profunda a la piel.",
        ingredients: "Ácido Hialurónico de bajo peso molecular, Aceite de Jengibre, Cúrcuma.",
        tag: "Recomendado" 
    },
    { 
        id: 36, 
        name: "Forever B12 Plus", 
        price: 295, 
        category: "Bienestar",
        image: "assets/p36.jpg", 
        descShort: "Vitamina B12 combinada con Ácido Fólico.",
        descFull: "Ayuda a la formación de glóbulos rojos, reduce el cansancio y combate la fatiga nerviosa. Esencial para vegetarianos.",
        ingredients: "Vitamina B12 (Cianocobalamina), Ácido Fólico (Vitamina B9).",
        tag: "Recomendado" 
    },
    { 
        id: 37, 
        name: "Forever Lycium Plus", 
        price: 520, 
        category: "Bienestar",
        image: "assets/p37.jpg", 
        descShort: "Extracto concentrado de Bayas de Goji y Regaliz.",
        descFull: "Poderoso tónico tónico antioxidante chino que protege la vista, la piel y las células del envejecimiento prematuro.",
        ingredients: "Extracto de fruto de Lycium (Goji), Extracto de raíz de Regaliz.",
        tag: "Especial" 
    },
    { 
        id: 38, 
        name: "Forever Multi-Maca", 
        price: 500, 
        category: "Bienestar",
        image: "assets/p38.jpg", 
        descShort: "Maca peruana combinada con L-Arginina y plantas energizantes.",
        descFull: "Aumenta la líbido, la fuerza física, la resistencia y la fertilidad tanto en hombres como en mujeres.",
        ingredients: "Raíz de Maca, L-Arginina, Tribulus Terrestris, Muira Puama, CoQ10.",
        tag: "Top Ventas" 
    },

    // --- DEPORTE Y CONTROL DE PESO ---
    { 
        id: 39, 
        name: "Forever Lite Ultra (Vainilla/Chocolate)", 
        price: 344, 
        category: "Packs",
        image: "assets/p39.jpg", 
        descShort: "Batido proteico vegetal con 17g de proteína por porción.",
        descFull: "Sustitutivo de comida ideal para tonificar músculos o como apoyo en programas de pérdida de peso saludables.",
        ingredients: "Aislado de Proteína de Soja, 18 aminoácidos, Vitaminas A, C, D, E.",
        tag: "Top Ventas" 
    },
    { 
        id: 40, 
        name: "Forever ARGI+", 
        price: 935, 
        category: "Bienestar",
        image: "assets/p40.jpg", 
        descShort: "L-Arginina con complejo vitamínico y extractos de frutas.",
        descFull: "Conocido como la 'molécula milagrosa'. Dilata los vasos sanguíneos para mayor rendimiento deportivo, salud cardíaca y energía íntima.",
        ingredients: "L-Arginina, Extracto de Granada, Uva tinta, Vitaminas C, D3, K2, B6, B12.",
        tag: "Top Ventas" 
    },
    { 
        id: 41, 
        name: "Aloe Blossom Herbal Tea", 
        price: 286, 
        category: "Bienestar",
        image: "assets/p41.jpg", 
        descShort: "Infusión relajante de flor de Aloe, canela y jengibre sin teína.",
        descFull: "Ayuda a conciliar el sueño, calma el estrés, favorece la digestión pesada y ayuda a eliminar la retención de líquidos.",
        ingredients: "Flores de Aloe, Canela, Jengibre, Cardamomo, Manzanilla, Clavo.",
        tag: "Recomendado" 
    },
    { 
        id: 42, 
        name: "Forever Therm", 
        price: 488, 
        category: "Packs",
        image: "assets/p42.jpg", 
        descShort: "Acelerador metabólico con Té Verde, Café Verde y Guaraná.",
        descFull: "Aumenta la termogénesis para quemar calorías eficientemente mientras proporciona un impulso inmediato de energía física.",
        ingredients: "Té verde, Café verde, Guaraná, Vitaminas del grupo B y Vitamina C.",
        tag: "Top Ventas" 
    },
    { 
        id: 43, 
        name: "Forever Lean", 
        price: 511, 
        category: "Packs",
        image: "assets/p43.jpg", 
        descShort: "Captador natural de grasas y carbohidratos con Cromo.",
        descFull: "Bloquea la absorción de calorías procedentes de los azúcares y grasas de las comidas, ayudando a controlar los antojos.",
        ingredients: "Extracto de Chumbera (Higo Chumbo), Judía Blanca, Cromo.",
        tag: "Recomendado" 
    },
    { 
        id: 44, 
        name: "Forever Garcinia Plus", 
        price: 500, 
        category: "Packs",
        image: "assets/p44.jpg", 
        descShort: "Inhibidor natural del apetito a base de Garcinia Cambogia.",
        descFull: "Frena la conversión de carbohidratos en grasas acumuladas y reduce la ansiedad por comer entre horas.",
        ingredients: "Extracto de Garcinia Cambogia (HCA), Aceite de Cártamo, Cromo.",
        tag: "Top Ventas" 
    },
    { 
        id: 45, 
        name: "FAB Forever Active Boost", 
        price: 46, 
        category: "Bienestar",
        image: "assets/p45.jpg", 
        descShort: "Bebida energética natural con Guaraná y Aloe Vera.",
        descFull: "Aporta energía limpia e inmediata para momentos de fatiga, deporte o jornadas largas de trabajo.",
        ingredients: "Guaraná, Mezcla de Hierbas adaptógenas, Gel de Aloe Vera, Vitaminas B.",
        tag: "Económico" 
    },
    { 
        id: 46, 
        name: "FAB X Forever Active Boost (Sin Azúcar)", 
        price: 46, 
        category: "Bienestar",
        image: "assets/p46.jpg", 
        descShort: "Bebida energética 0% azúcar y 0% calorías.",
        descFull: "Toda la energía revitalizante del FAB original en una versión saludable sin calorías.",
        ingredients: "Guaraná, Vitaminas B, Electrolitos, Cero Azúcares.",
        tag: "Económico" 
    },
    { 
        id: 47, 
        name: "Pack Detox C9 / Svelte", 
        price: 1616, 
        category: "Packs",
        image: "assets/p47.jpg", 
        descShort: "Programa intensivo de 9 días para purificar el organismo.",
        descFull: "Limpia las toxinas atrapadas, aumenta los niveles de energía y favorece una pérdida de 3 a 7 kg en 9 días.",
        ingredients: "2x Aloe Vera Gel, 1x Lite Ultra, 1x Fields of Greens, 1x Pro-B + accesorios.",
        tag: "Ahorro" 
    },
    { 
        id: 48, 
        name: "Baque Mansour (30 Días)", 
        price: 3733, 
        category: "Packs",
        image: "assets/p48.jpg", 
        descShort: "Programa completo de remodelación corporal de 30 días.",
        descFull: "Continuación directa del C9. Diseñado para quemar grasa rebelde acumulada y lograr una pérdida de 12 a 20 kg.",
        ingredients: "4x Aloe Vera Gel, 2x Lite Ultra, Fiber, Pro-B, Bee Pollen, Absorbent-C.",
        tag: "Ahorro" 
    },

    // --- CUIDADO PERSONAL Y COSMÉTICA ---
    { 
        id: 49, 
        name: "Forever Bright Toothgel", 
        price: 125, 
        category: "Cuidado Personal",
        image: "assets/p49.jpg", 
        descShort: "Pasta dental de Aloe Vera y Própolis sin flúor ni abrasivos.",
        descFull: "Blanquea suavemente, calma las encías sensibles, combate el sangrado bucal y deja un aliento fresco de larga duración.",
        ingredients: "Gel de Aloe Vera puro, Própolis de Abeja, Menta natural.",
        tag: "Top Ventas" 
    },
    { 
        id: 50, 
        name: "Aloe Ever-Shield Deodorant", 
        price: 116, 
        category: "Cuidado Personal",
        image: "assets/p50.jpg", 
        descShort: "Desodorante en barra sin sales de aluminio ni alcohol.",
        descFull: "Protección efectiva todo el día contra el mal olor sin obstruir los poros ni manchar la ropa. Apto inmediatamente tras el depilado.",
        ingredients: "Gel de Aloe Vera estabilizado sin sales de aluminio.",
        tag: "Top Ventas" 
    },
    { 
        id: 51, 
        name: "Aloe Lips", 
        price: 57, 
        category: "Cuidado Personal",
        image: "assets/p51.jpg", 
        descShort: "Bálsamo labial hidratante con Aloe Vera y Jojoba.",
        descFull: "Alivia de inmediato los labios cortados, quemaduras leves, picaduras de insectos o rozaduras en la piel.",
        ingredients: "Aloe Vera, Aceite de Jojoba, Cera de abeja pura.",
        tag: "Popular" 
    },
    { 
        id: 52, 
        name: "Aloe Avocado Face & Body Soap", 
        price: 80, 
        category: "Cuidado Personal",
        image: "assets/p52.jpg", 
        descShort: "Pastilla de jabón enriquecida con manteca de Aguacate pura.",
        descFull: "Limpia e hidrata suavemente todo tipo de pieles, especialmente las grasas o mixtas, dejando un delicado aroma cítrico.",
        ingredients: "Manteca de Aguacate puro, Gel de Aloe Vera.",
        tag: "Top Ventas" 
    },
    { 
        id: 53, 
        name: "Aloe Liquid Soap", 
        price: 255, 
        category: "Cuidado Personal",
        image: "assets/p53.jpg", 
        descShort: "Jabón líquido concentrado para manos, rostro y cuerpo.",
        descFull: "Fórmula ultramórbida respetuosa con las pieles más delicadas o reactivas. Limpia sin resecar creando una espuma cremosa.",
        ingredients: "Aloe Vera, Aceite de Argán, Extracto de Pepino, Jojoba.",
        tag: "Recomendado" 
    },
    { 
        id: 54, 
        name: "Aloe Body Wash", 
        price: 296, 
        category: "Cuidado Personal",
        image: "assets/p54.jpg", 
        descShort: "Gel de ducha relajante pH equilibrado con aroma botánico.",
        descFull: "Limpia con delicadeza manteniendo la barrera cutánea hidratada gracias a sus aceites naturales y vitaminas.",
        ingredients: "Aloe Vera, Aceite de Argán, Flor de Árnica, Vitaminas A, C, E.",
        tag: "Nuevo" 
    },
    { 
        id: 55, 
        name: "Aloe-Jojoba Shampoo", 
        price: 287, 
        category: "Cuidado Personal",
        image: "assets/p55.jpg", 
        descShort: "Champú nutritivo concentrado sin sulfatos.",
        descFull: "Elimina la caspa, calma el picor del cuero cabelludo, fortalece el cabello fino y devuelve el brillo natural.",
        ingredients: "Aloe Vera, Aceite de Jojoba, Aceite de Argán, Aceite de Rosa Mosqueta.",
        tag: "Top Ventas" 
    },
    { 
        id: 56, 
        name: "Aloe-Jojoba Conditioner", 
        price: 307, 
        category: "Cuidado Personal",
        image: "assets/p56.jpg", 
        descShort: "Acondicionador suavizante antiencrespamiento sin sulfatos.",
        descFull: "Desenreda instantáneamente, sella las puntas abiertas y aporta suavidad sin apelmazar la melena.",
        ingredients: "Aloe Vera, Aceite de Jojoba, Argán, Lavanda, Girasol.",
        tag: "Recomendado" 
    },
    { 
        id: 57, 
        name: "Nourishing Hair Oil", 
        price: 369, 
        category: "Cuidado Personal",
        image: "assets/p57.jpg", 
        descShort: "Sérum de aceites botánicos ligeros sin siliconas.",
        descFull: "Nutre el cabello seco o castigado por tintes. Controla la humedad, aporta brillo radiante y es apto para el cuidado de la barba.",
        ingredients: "Aloe Vera, Aceite de Jojoba, Fitoesteroles, Ésteres vegetales.",
        tag: "Nuevo" 
    },
    { 
        id: 58, 
        name: "Aloe First Spray", 
        price: 322, 
        category: "Cuidado Personal",
        image: "assets/p58.jpg", 
        descShort: "Spray calmante multiusos con Aloe, Própolis y 11 plantas.",
        descFull: "Alivia rojeces, quemaduras solares, irritaciones tras la depilación o afeitado, eczemas y acondiciona el cuero cabelludo.",
        ingredients: "Gel de Aloe Vera (78%), Própolis, Manzanilla, Caléndula, Tomillo.",
        tag: "Top Ventas" 
    },
    { 
        id: 59, 
        name: "Aloe Vera Gelly", 
        price: 242, 
        category: "Cosmética",
        image: "assets/p59.jpg", 
        descShort: "Gel 100% transparente de Aloe Vera puro en tubo.",
        descFull: "El botiquín en tubo: alivia instantáneamente rozaduras, picaduras, quemaduras leves, acné y calma pieles irritadas.",
        ingredients: "100% Gel de Aloe Vera estabilizado, Vitamina E.",
        tag: "Top Ventas" 
    },
    { 
        id: 60, 
        name: "Aloe Propolis Creme", 
        price: 322, 
        category: "Cosmética",
        image: "assets/p60.jpg", 
        descShort: "Crema densa para pieles con acné, sequedad o eczemas.",
        descFull: "Combina Aloe Vera y Própolis para crear un potente bálsamo reparador contra cicatrices de acné, manchas y sequedad extrema.",
        ingredients: "Gel de Aloe Vera, Própolis de Abeja, Manzanilla, Vitaminas A y E.",
        tag: "Top Ventas" 
    },
    { 
        id: 61, 
        name: "Aloe Moisturizing Lotion", 
        price: 242, 
        category: "Cosmética",
        image: "assets/p61.jpg", 
        descShort: "Loción fluida con Colágeno y Elastina para cutis seco.",
        descFull: "Restaura la barrera hídrica de la piel gastada por el viento o el sol. Ideal como base preparadora antes del maquillaje.",
        ingredients: "Aloe Vera, Colágeno, Elastina, Aceite de Jojoba, Vitamina E.",
        tag: "Recomendado" 
    },
    { 
        id: 62, 
        name: "Aloe Body Lotion", 
        price: 299, 
        category: "Cosmética",
        image: "assets/p62.jpg", 
        descShort: "Hidratante corporal rápida absorción con aceite de Argán.",
        descFull: "Deja la piel suave, elástica y nutrida sin residuo graso. Previene la descamación e irritaciones corporales.",
        ingredients: "Aloe Vera, Aceite de Argán, Aceite de Macadamia, Ésteres de Jojoba.",
        tag: "Nuevo" 
    },
    { 
        id: 63, 
        name: "Aloe Cooling Lotion", 
        price: 190, 
        category: "Cuidado Personal",
        image: "assets/p63.jpg", 
        descShort: "Loción refrescante de masaje con Mentol y Eucalipto.",
        descFull: "Efecto frío inmediato para calmar la pesadez de piernas, pies cansados y tensión muscular tras el ejercicio.",
        ingredients: "Gel de Aloe Vera, Mentol, Aceite de Eucalipto, Romero, Alcanfor.",
        tag: "Nuevo" 
    },
    { 
        id: 64, 
        name: "Aloe Heat Lotion", 
        price: 242, 
        category: "Cuidado Personal",
        image: "assets/p64.jpg", 
        descShort: "Loción de masaje con efecto calor para contracturas.",
        descFull: "Alivia agujetas, tirones musculares, rigidez en el cuello o espalda y descongestiona el pecho durante resfriados.",
        ingredients: "Aloe Vera, Aceite de Eucalipto, Mentol, Salicilato de Metilo.",
        tag: "Top Ventas" 
    },
    { 
        id: 65, 
        name: "Aloe MSM Gel", 
        price: 376, 
        category: "Cuidado Personal",
        image: "assets/p65.jpg", 
        descShort: "Gel transparente de azufre orgánico MSM para articulaciones.",
        descFull: "Calma los dolores articulares, inflamaciones por golpes o torceduras y favorece la regeneración del cartílago.",
        ingredients: "Gel de Aloe Vera, MSM (Metilsulfonilmetano), Romero, Salvia.",
        tag: "Recomendado" 
    },
    { 
        id: 66, 
        name: "Gentleman's Pride", 
        price: 242, 
        category: "Cuidado Personal",
        image: "assets/p66.jpg", 
        descShort: "Bálsamo para después del afeitado sin alcohol.",
        descFull: "Calma la irritación de la cuchilla, refresca la cara y previene los pelos encarnados con una fragancia masculina suave.",
        ingredients: "Aloe Vera, Romero, Manzanilla, Pepino.",
        tag: "Top Ventas" 
    },
    { 
        id: 67, 
        name: "Smoothing Exfoliator", 
        price: 239, 
        category: "Cosmética",
        image: "assets/p67.jpg", 
        descShort: "Exfoliante facial suave con perlas de Jojoba y Bambú.",
        descFull: "Elimina células muertas y puntos negros sin agredir la piel, dejando el rostro suave y luminoso.",
        ingredients: "Aloe Vera, Perlas de Jojoba, Polvo de Bambú, Enzimas de Piña.",
        tag: "Recomendado" 
    },
    { 
        id: 68, 
        name: "Balancing Toner", 
        price: 286, 
        category: "Cosmética",
        image: "assets/p68.jpg", 
        descShort: "Tónico equilibrante de pH con extracto de algas y pepino.",
        descFull: "Minimiza los poros dilatados, equilibra la hidratación del rostro y prepara el cutis para cremas o sérums.",
        ingredients: "Aloe Vera, Extracto de Pepino, Algas marinas, Hialuronato sódico.",
        tag: "Nuevo" 
    },
    { 
        id: 69, 
        name: "Awakening Eye Cream", 
        price: 239, 
        category: "Cosmética",
        image: "assets/p69.jpg", 
        descShort: "Contorno de ojos contra ojeras, bolsas y arrugas.",
        descFull: "Tensa la fina piel de los párpados, disminuye el tono oscuro de las ojeras y reduce visiblemente la hinchazón matutina.",
        ingredients: "Aloe Vera, Péptidos colágenos, Extracto de Corteza de Albizia.",
        tag: "Top Ventas" 
    },
    { 
        id: 70, 
        name: "Aloe Activator", 
        price: 210, 
        category: "Cosmética",
        image: "assets/p70.jpg", 
        descShort: "Líquido de Aloe Vera ultrapuro purificado (98.9%).",
        descFull: "Enriquece mascarillas, calma irritaciones oculares leves, limpia suavemente la cara y refresca los poros.",
        ingredients: "98.9% Gel de Aloe Vera filtrado, Alantoína.",
        tag: "Recomendado" 
    },
    { 
        id: 71, 
        name: "Aloe Bio-Cellulose Mask (Pack 5)", 
        price: 439, 
        category: "Cosmética",
        image: "assets/p71.jpg", 
        descShort: "Mascarilla de biocelulosa de alta penetración antiedad.",
        descFull: "Penetra en las capas más profundas del rostro aportando hidratación intensiva, firmeza y resplandor inmediato.",
        ingredients: "Aloe Vera fermentado, Té verde, Castaño de Indias, Algas.",
        tag: "Lujo" 
    },
    { 
        id: 72, 
        name: "Deep Moisturizing Cream", 
        price: 442, 
        category: "Cosmética",
        image: "assets/p72.jpg", 
        descShort: "Crema ultra-nutritiva con pino blanco y aceite de jojoba.",
        descFull: "Combate la sequedad extrema y las arrugas profundas restaurando la elasticidad del cutis apagado.",
        ingredients: "Aloe Vera, Extracto de Corteza de Pino Blanco, Ceramidas.",
        tag: "Top Ventas" 
    },
    { 
        id: 73, 
        name: "Replenishing Oil Skin", 
        price: 402, 
        category: "Cosmética",
        image: "assets/p73.jpg", 
        descShort: "Sérum oleoso concentrado rico en vitaminas A, C y E.",
        descFull: "Nutrición intensiva para pieles muy secas o envejecidas. Restaura la flexibilidad sin sensación grasa pesada.",
        ingredients: "Aceite de Semilla de Borraja, Bisabolol, Vitaminas A, C, E.",
        tag: "Recomendado" 
    },
    { 
        id: 74, 
        name: "Hydrating Serum", 
        price: 462, 
        category: "Cosmética",
        image: "assets/p74.jpg", 
        descShort: "Sérum ultraligero con 4 tipos de ácido hialurónico.",
        descFull: "Escudo hidratante contra la contaminación que rellena las arrugas finas y suaviza la textura de la piel.",
        ingredients: "Aloe Vera, 4 formas de Ácido Hialurónico, Té Verde.",
        tag: "Top Ventas" 
    },
    { 
        id: 75, 
        name: "Logic Gel Nettoyant", 
        price: 346, 
        category: "Cosmética",
        image: "assets/p75.jpg", 
        descShort: "Gel limpiador purificante con extractos de manzana y limón.",
        descFull: "Elimina restos de maquillaje y grasa sin alterar el nivel hídrico natural del rostro.",
        ingredients: "Aloe Vera, Extracto de Pepino, Limón, Manzana.",
        tag: "Nuevo" 
    },
    { 
        id: 76, 
        name: "Logic Essence Toner", 
        price: 333, 
        category: "Cosmética",
        image: "assets/p76.jpg", 
        descShort: "Esencia tónica mico-encapsulada con té verde.",
        descFull: "Aporta luminosidad, cierra poros y equilibra la piel cansada con potentes antioxidantes vegetales.",
        ingredients: "Aloe Vera, Hialuronato Sódico, Pepino, Té Verde, Algas.",
        tag: "Nuevo" 
    },
    { 
        id: 77, 
        name: "Logic Gel Hydratant", 
        price: 367, 
        category: "Cosmética",
        image: "assets/p77.jpg", 
        descShort: "Gel hidratante calmante con aceite de Girasol.",
        descFull: "Textura ligera de rápida absorción que refresca, nutre y previene las primeras arrugas de expresión.",
        ingredients: "Aloe Vera, Manzana, Girasol, Pepino, Té verde.",
        tag: "Nuevo" 
    },
    { 
        id: 78, 
        name: "Forever Vitamin C Creme", 
        price: 750, 
        category: "Cosmética",
        image: "assets/p78.jpg", 
        descShort: "Tratamiento iluminador intensivo con Vitamina C y E.",
        descFull: "Unifica el tono del rostro, reduce manchas solares y estimula la firmeza de la piel fatigada.",
        ingredients: "Vitamina C estable, Vitamina E, Aloe Vera, Algas Rojas.",
        tag: "Lujo" 
    },
    { 
        id: 79, 
        name: "Forever Bakuchiol", 
        price: 750, 
        category: "Cosmética",
        image: "assets/p79.jpg", 
        descShort: "Alternativa 100% vegetal al retinol sin irritación.",
        descFull: "Reduce las arrugas, mejora la firmeza y atenúa las manchas oscuras. Apto para las pieles más sensibles.",
        ingredients: "Bakuchiol puro, Aloe Vera, Ésteres de Jojoba, Pantenol (B5).",
        tag: "Lujo" 
    },
    { 
        id: 80, 
        name: "Infinite by Forever (Set Antienvejecimiento)", 
        price: 2301, 
        category: "Packs",
        image: "assets/p80.jpg", 
        descShort: "Cofre de cosmética avanzada con colágeno e ingredientes activos.",
        descFull: "Tratamiento global antiedad que incluye limpiador, sérum reafirmante, suplemento nutricional de belleza y crema restauradora.",
        ingredients: "Aloe Vera, Colágeno Marino, Péptidos, Extractos botánicos.",
        tag: "Ahorro" 
    },

    // --- FRAGANCIAS Y OTROS ---
    { 
        id: 81, 
        name: "Forever Malosi Fine Fragrance (Hombre)", 
        price: 446, 
        category: "Cuidado Personal",
        image: "assets/p81.jpg", 
        descShort: "Perfume masculino elegante con madera de Sándalo y Bergamota.",
        descFull: "Aroma amaderado fresco y sofisticado diseñado para el hombre moderno. Excelente fijación de larga duración.",
        ingredients: "Madera de Sándalo, Bergamota, Cítricos, Ciprés.",
        tag: "Lujo" 
    },
    { 
        id: 82, 
        name: "Forever Alofa Fine Fragrance (Mujer)", 
        price: 446, 
        category: "Cuidado Personal",
        image: "assets/p82.jpg", 
        descShort: "Perfume femenino cautivador con Jazmín y Cítricos.",
        descFull: "Fragancia cálida y envolvente con notas florales dulces mezcladas con sándalo reconfortante.",
        ingredients: "Jazmín Dulce, Cítricos frescos, Madera de Sándalo.",
        tag: "Lujo" 
    },
    { 
        id: 83, 
        name: "Forever Freedom", 
        price: 581, 
        category: "Bienestar",
        image: "assets/p83.jpg", 
        descShort: "Gel de Aloe Vera formulado para la salud articular.",
        descFull: "Combina Aloe Vera con Sulfato de Glucosamina y Condroitina para conservar la lubricación y cartílago de los huesos.",
        ingredients: "Gel de Aloe Vera, Glucosamina, Condroitina, MSM, Vitamina C.",
        tag: "Top Ventas" 
    },
    { 
        id: 84, 
        name: "Forever Scrub", 
        price: 260, 
        category: "Cosmética",
        image: "assets/p84.jpg", 
        descShort: "Exfoliante corporal y facial con microesferas de Jojoba.",
        descFull: "Limpia los poros en profundidad arrastrando la grasa acumulada sin rayar ni irritar la epidermis.",
        ingredients: "Gel de Aloe Vera, Aceite de Jojoba, Aceite de Soja, Vitamina C.",
        tag: "Recomendado" 
    },
    // --- LÍNEA SONYA, HOGAR Y ACEITES ESENCIALES (85 A 95) ---
    { 
        id: 85, 
        name: "Sonya Daily Skincare System", 
        price: 1042, 
        category: "Packs",
        image: "assets/p85.jpg", 
        descShort: "Sistema de cuidado facial a base de gel para pieles mixtas.",
        descFull: "Controla el exceso de grasa e hidrata donde más se necesita. Incluye limpiador, gel iluminador, mascarilla refinadora y gel hidratante.",
        ingredients: "Aloe Vera, Aminoácidos de manzana, Extractos botánicos asiáticos.",
        tag: "Ahorro" 
    },
    { 
        id: 86, 
        name: "Sonya Refreshing Gel Cleanser", 
        price: 286, 
        category: "Cosmética",
        image: "assets/p86.jpg", 
        descShort: "Gel limpiador facial suave que genera una espuma acondicionadora.",
        descFull: "Limpia profundamente sin estirar ni resecar la piel sensible o mixta, removiendo suciedad y maquillaje con delicadeza.",
        ingredients: "Aloe Vera, Aceite de Baobab prensado en frío, Aminoácidos de manzana.",
        tag: "Recomendado" 
    },
    { 
        id: 87, 
        name: "Sonya Illuminating Gel", 
        price: 271, 
        category: "Cosmética",
        image: "assets/p87.jpg", 
        descShort: "Gel iluminador para dar un brillo natural y controlar el tono.",
        descFull: "Ayuda a unificar el tono de la piel, disuadir manchas y aportar un resplandor radiante a los rostros apagados.",
        ingredients: "Aloe Vera, Raíz de Regaliz, Mezcla de algas verdes y marrones.",
        tag: "Nuevo" 
    },
    { 
        id: 88, 
        name: "Sonya Refining Gel Mask", 
        price: 286, 
        category: "Cosmética",
        image: "assets/p88.jpg", 
        descShort: "Mascarilla nocturna que equilibra la grasa mientras duermes.",
        descFull: "Aplica antes de dormir para levantarte con una piel fresca, equilibrada, suave y con poros visiblemente atenuados.",
        ingredients: "Aloe Vera, Aceite de Zanahoria, Extracto de Fruto de Manzana, Albizia.",
        tag: "Popular" 
    },
    { 
        id: 89, 
        name: "Sonya Soothing Gel Moisturizer", 
        price: 318, 
        category: "Cosmética",
        image: "assets/p89.jpg", 
        descShort: "Hidratante en gel rico en colágeno e ingredientes botánicos.",
        descFull: "Mantiene la piel hidratada sin recargarla de grasa, dejando una sensación suave, fresca y sin brillos indeseados.",
        ingredients: "Aloe Vera, Ésteres de Jojoba, Aceite de Naranja, Colágeno hidrolizado.",
        tag: "Recomendado" 
    },
    { 
        id: 90, 
        name: "Forever MPD 2X Ultra", 
        price: 337, 
        category: "Cuidado Personal",
        image: "assets/p90.jpg", 
        descShort: "Detergente líquido concentrado, biodegradable y multiusos.",
        descFull: "Limpia ropa, vajilla, suelos, baños y azulejos. Fórmula respetuosa con el medio ambiente y suave con las manos.",
        ingredients: "Tensioactivos biodegradables, Gel de Aloe Vera.",
        tag: "Ecológico" 
    },
    { 
        id: 91, 
        name: "Forever Instant Hand Cleanser", 
        price: 160, 
        category: "Cuidado Personal",
        image: "assets/p91.jpg", 
        descShort: "Gel limpiador higienizante de manos con aroma cítrico.",
        descFull: "Limpia e higieniza tus manos al instante sin necesidad de agua ni aclarado, evitando la sequedad gracias al Aloe Vera.",
        ingredients: "Alcohol, Gel de Aloe Vera, Aceite de Cítricos.",
        tag: "Práctico" 
    },
    { 
        id: 92, 
        name: "Forever FastBreak Bar", 
        price: 48, 
        category: "Bienestar",
        image: "assets/p92.jpg", 
        descShort: "Barrita proteica sabor manteca de cacahuete y chocolate.",
        descFull: "Aporta 11g de proteína, fibra, vitaminas y minerales. La merienda o snack perfecto para saciar el hambre entre horas.",
        ingredients: "Proteína de Soja, Cacahuetes, Chocolate, Complejo vitamínico.",
        tag: "Económico" 
    },
    { 
        id: 93, 
        name: "Forever Essential Oils - Lavender", 
        price: 312, 
        category: "Bienestar",
        image: "assets/p93.jpg", 
        descShort: "Aceite esencial de lavanda 100% puro para relajación.",
        descFull: "Favorece el descanso nocturno, reduce la ansiedad y alivia el estrés cuando se usa en difusor o masaje diluido.",
        ingredients: "100% Aceite Esencial de Lavanda pura (Lavandula Angustifolia).",
        tag: "Esencial" 
    },
    { 
        id: 94, 
        name: "Forever Essential Oils - Peppermint", 
        price: 242, 
        category: "Bienestar",
        image: "assets/p94.jpg", 
        descShort: "Aceite esencial de menta piperita pura estimulante.",
        descFull: "Revitaliza la mente, despeja la respiración y alivia dolores de cabeza leves mediante aromaterapia.",
        ingredients: "100% Aceite Esencial de Menta Piperita pura.",
        tag: "Esencial" 
    },
    { 
        id: 95, 
        name: "Programa DX4 Body Balancing System", 
        price: 1580, 
        category: "Packs",
        image: "assets/p95.jpg", 
        descShort: "Programa de 4 días para reajustar cuerpo y mente.",
        descFull: "Sistema de nutrición intensiva que equilibra el metabolismo, frena la ansiedad por la comida y revitaliza el cuerpo.",
        ingredients: "4x Aloe Vera Gel Mini, Plant-Protein, Therm Plus, Reset, DuoPure, Multi-Fizz, LemonBlast.",
        tag: "Nuevo" 
    }
];